name: Check for New DEV Blog Post Comments and Add to Orbit
on:
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:
    branches:
      - main
jobs:
  comments-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Set up Ruby 2.7.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Bundle Install
      run: |
        gem update --system 3.1.4 -N
        gem install --no-document bundler
        bundle config path vendor/bundle
        bundle install dev_orbit --jobs 4 --retry 3
    - name: Check for New Comments
      run: |
        bundle exec dev_orbit --check-comments
      env:
        DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
        DEV_USERNAME: ${{ secrets.DEV_USERNAME }}
        ORBIT_API_KEY: ${{ secrets.ORBIT_API_KEY }}
        ORBIT_WORKSPACE_ID: ${{ secrets.ORBIT_WORKSPACE_ID }}
